CFLAGS=-I/opt/SDL-2.0.5/SDL2-2.0.5/i686-w64-mingw32/include -Dmain=SDL_main -Wall
LIBS=-L/opt/SDL-2.0.5/SDL2-2.0.5/i686-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows
CC=i686-w64-mingw32-gcc
TARGETS=netris.c
OUTPUT=out/netris.exe

default: clean all

PHONY: clean default

clean:
	@echo Cleaning...
	rm -f $(OUTPUT)
	rm -f *~
	@echo Done.

all: $(TARGETS) 
	$(CC) $(CFLAGS) $(TARGETS) -o $(OUTPUT) $(LIBS)
	cp $(OUTPUT) ~/shared/Shared/
